// 四级自习室 · 词典模块
// 点词翻译：先查「本课生词」→ 再查「内置四级词库」→ 可联网查英文词典

// 内置四级高频词表（音标 | 释义）
const BUILTIN_DICT = {
  "abandon": "/əˈbændən/ | v. 放弃；抛弃",
  "ability": "/əˈbɪləti/ | n. 能力；才能",
  "abroad": "/əˈbrɔːd/ | adv. 在国外；到国外",
  "absence": "/ˈæbsəns/ | n. 缺席；缺乏",
  "absolute": "/ˈæbsəluːt/ | adj. 绝对的；完全的",
  "absorb": "/əbˈzɔːb/ | v. 吸收；使专注",
  "abstract": "/ˈæbstrækt/ | adj. 抽象的 n. 摘要",
  "abundant": "/əˈbʌndənt/ | adj. 丰富的；充裕的",
  "abuse": "/əˈbjuːz/ | v./n. 滥用；虐待",
  "academic": "/ˌækəˈdemɪk/ | adj. 学术的；学业的",
  "accelerate": "/əkˈseləreɪt/ | v. 加速；促进",
  "access": "/ˈækses/ | n. 通道；使用权 v. 访问",
  "accommodate": "/əˈkɒmədeɪt/ | v. 容纳；使适应",
  "accompany": "/əˈkʌmpəni/ | v. 陪伴；伴随",
  "accomplish": "/əˈkʌmplɪʃ/ | v. 完成；实现",
  "account": "/əˈkaʊnt/ | n. 账户；描述 v. 解释",
  "accumulate": "/əˈkjuːmjəleɪt/ | v. 积累；堆积",
  "accurate": "/ˈækjərət/ | adj. 准确的；精确的",
  "accuse": "/əˈkjuːz/ | v. 指责；控告",
  "achieve": "/əˈtʃiːv/ | v. 实现；达到",
  "acknowledge": "/əkˈnɒlɪdʒ/ | v. 承认；致谢",
  "acquire": "/əˈkwaɪə(r)/ | v. 获得；习得",
  "adapt": "/əˈdæpt/ | v. 适应；改编",
  "adequate": "/ˈædɪkwət/ | adj. 足够的；适当的",
  "adjust": "/əˈdʒʌst/ | v. 调整；适应",
  "administration": "/ədˌmɪnɪˈstreɪʃn/ | n. 管理；行政部门",
  "admire": "/ədˈmaɪə(r)/ | v. 钦佩；欣赏",
  "admit": "/ədˈmɪt/ | v. 承认；准许进入",
  "adopt": "/əˈdɒpt/ | v. 采纳；收养",
  "advance": "/ədˈvɑːns/ | v./n. 前进；进步",
  "advantage": "/ədˈvɑːntɪdʒ/ | n. 优势；有利条件",
  "advertise": "/ˈædvətaɪz/ | v. 做广告；宣传",
  "advocate": "/ˈædvəkeɪt/ | v. 提倡 n. 拥护者",
  "affect": "/əˈfekt/ | v. 影响；感动",
  "afford": "/əˈfɔːd/ | v. 负担得起；提供",
  "agency": "/ˈeɪdʒənsi/ | n. 机构；代理",
  "aggressive": "/əˈɡresɪv/ | adj. 好斗的；进取的",
  "agriculture": "/ˈæɡrɪkʌltʃə(r)/ | n. 农业",
  "aid": "/eɪd/ | n./v. 帮助；援助",
  "aim": "/eɪm/ | n. 目标 v. 旨在",
  "alarm": "/əˈlɑːm/ | n. 警报；惊恐",
  "alter": "/ˈɔːltə(r)/ | v. 改变；修改",
  "alternative": "/ɔːlˈtɜːnətɪv/ | n. 替代方案 adj. 替代的",
  "ambition": "/æmˈbɪʃn/ | n. 雄心；抱负",
  "amount": "/əˈmaʊnt/ | n. 数量；总额",
  "analyze": "/ˈænəlaɪz/ | v. 分析",
  "ancestor": "/ˈænsestə(r)/ | n. 祖先",
  "announce": "/əˈnaʊns/ | v. 宣布；通告",
  "annual": "/ˈænjuəl/ | adj. 每年的 n. 年刊",
  "anticipate": "/ænˈtɪsɪpeɪt/ | v. 预期；预料",
  "anxiety": "/æŋˈzaɪəti/ | n. 焦虑；忧虑",
  "apparent": "/əˈpærənt/ | adj. 明显的；表面上的",
  "appeal": "/əˈpiːl/ | v./n. 呼吁；吸引",
  "appetite": "/ˈæpɪtaɪt/ | n. 食欲；欲望",
  "applaud": "/əˈplɔːd/ | v. 鼓掌；称赞",
  "apply": "/əˈplaɪ/ | v. 申请；应用",
  "appoint": "/əˈpɔɪnt/ | v. 任命；约定",
  "appreciate": "/əˈpriːʃieɪt/ | v. 欣赏；感激",
  "approach": "/əˈprəʊtʃ/ | n. 方法；途径 v. 接近",
  "appropriate": "/əˈprəʊpriət/ | adj. 适当的；恰当的",
  "approve": "/əˈpruːv/ | v. 批准；赞成",
  "approximate": "/əˈprɒksɪmət/ | adj. 大约的；近似的",
  "arbitrary": "/ˈɑːbɪtrəri/ | adj. 任意的；武断的",
  "argue": "/ˈɑːɡjuː/ | v. 争论；主张",
  "arise": "/əˈraɪz/ | v. 出现；产生",
  "arrange": "/əˈreɪndʒ/ | v. 安排；整理",
  "artificial": "/ˌɑːtɪˈfɪʃl/ | adj. 人造的；人工的",
  "aspect": "/ˈæspekt/ | n. 方面；外观",
  "assemble": "/əˈsembl/ | v. 集合；组装",
  "assess": "/əˈses/ | v. 评估；评定",
  "assign": "/əˈsaɪn/ | v. 分配；指派",
  "assist": "/əˈsɪst/ | v. 帮助；协助",
  "associate": "/əˈsəʊʃieɪt/ | v. 联想；交往",
  "assume": "/əˈsjuːm/ | v. 假定；承担",
  "assure": "/əˈʃʊə(r)/ | v. 保证；使确信",
  "astonish": "/əˈstɒnɪʃ/ | v. 使惊讶",
  "atmosphere": "/ˈætməsfɪə(r)/ | n. 大气；气氛",
  "attach": "/əˈtætʃ/ | v. 附上；依恋",
  "attain": "/əˈteɪn/ | v. 达到；获得",
  "attempt": "/əˈtempt/ | v./n. 尝试；企图",
  "attitude": "/ˈætɪtjuːd/ | n. 态度；看法",
  "attract": "/əˈtrækt/ | v. 吸引",
  "audience": "/ˈɔːdiəns/ | n. 观众；听众",
  "authority": "/ɔːˈθɒrəti/ | n. 权威；当局",
  "available": "/əˈveɪləbl/ | adj. 可获得的；有空的",
  "average": "/ˈævərɪdʒ/ | adj./n. 平均的；平均数",
  "avoid": "/əˈvɔɪd/ | v. 避免；避开",
  "award": "/əˈwɔːd/ | n. 奖 v. 授予",
  "aware": "/əˈweə(r)/ | adj. 意识到的；知道的",
  "balance": "/ˈbæləns/ | n. 平衡 v. 使平衡",
  "barrier": "/ˈbæriə(r)/ | n. 障碍；屏障",
  "benefit": "/ˈbenɪfɪt/ | n. 好处 v. 受益",
  "blame": "/bleɪm/ | v./n. 责备；归咎",
  "boost": "/buːst/ | v./n. 促进；提升",
  "boundary": "/ˈbaʊndri/ | n. 边界；界限",
  "budget": "/ˈbʌdʒɪt/ | n. 预算",
  "burden": "/ˈbɜːdn/ | n. 负担 v. 使负重",
  "campaign": "/kæmˈpeɪn/ | n. 运动；战役",
  "candidate": "/ˈkændɪdət/ | n. 候选人；应试者",
  "capacity": "/kəˈpæsəti/ | n. 容量；能力",
  "career": "/kəˈrɪə(r)/ | n. 职业；事业",
  "category": "/ˈkætəɡəri/ | n. 类别；范畴",
  "caution": "/ˈkɔːʃn/ | n. 小心；警告",
  "celebrate": "/ˈselɪbreɪt/ | v. 庆祝",
  "challenge": "/ˈtʃælɪndʒ/ | n./v. 挑战",
  "characteristic": "/ˌkærəktəˈrɪstɪk/ | n. 特征 adj. 典型的",
  "circumstance": "/ˈsɜːkəmstəns/ | n. 环境；情况",
  "civilization": "/ˌsɪvəlaɪˈzeɪʃn/ | n. 文明",
  "claim": "/kleɪm/ | v./n. 声称；索取",
  "classify": "/ˈklæsɪfaɪ/ | v. 分类",
  "collapse": "/kəˈlæps/ | v./n. 倒塌；崩溃",
  "combine": "/kəmˈbaɪn/ | v. 结合；联合",
  "commercial": "/kəˈmɜːʃl/ | adj. 商业的 n. 广告",
  "commit": "/kəˈmɪt/ | v. 犯（罪）；承诺",
  "community": "/kəˈmjuːnəti/ | n. 社区；群体",
  "compete": "/kəmˈpiːt/ | v. 竞争；比赛",
  "complex": "/ˈkɒmpleks/ | adj. 复杂的 n. 综合体",
  "component": "/kəmˈpəʊnənt/ | n. 组成部分；成分",
  "comprehensive": "/ˌkɒmprɪˈhensɪv/ | adj. 全面的；综合的",
  "concentrate": "/ˈkɒnsntreɪt/ | v. 集中；专心",
  "concept": "/ˈkɒnsept/ | n. 概念；观念",
  "concern": "/kənˈsɜːn/ | n./v. 关心；担忧",
  "conclude": "/kənˈkluːd/ | v. 得出结论；结束",
  "conduct": "/kənˈdʌkt/ | v. 进行；实施；指挥",
  "confidence": "/ˈkɒnfɪdəns/ | n. 信心；信任",
  "confirm": "/kənˈfɜːm/ | v. 确认；证实",
  "conflict": "/ˈkɒnflɪkt/ | n. 冲突 v. 抵触",
  "confront": "/kənˈfrʌnt/ | v. 面对；对抗",
  "consequence": "/ˈkɒnsɪkwəns/ | n. 结果；后果",
  "conservation": "/ˌkɒnsəˈveɪʃn/ | n. 保护；保存",
  "considerable": "/kənˈsɪdərəbl/ | adj. 相当大的；重要的",
  "consist": "/kənˈsɪst/ | v. 组成；在于",
  "constant": "/ˈkɒnstənt/ | adj. 持续的；不变的",
  "construct": "/kənˈstrʌkt/ | v. 建造；构建",
  "consume": "/kənˈsjuːm/ | v. 消耗；消费",
  "contain": "/kənˈteɪn/ | v. 包含；容纳",
  "contemporary": "/kənˈtemprəri/ | adj. 当代的；同时代的",
  "contribute": "/kənˈtrɪbjuːt/ | v. 贡献；促成",
  "controversial": "/ˌkɒntrəˈvɜːʃl/ | adj. 有争议的",
  "convenient": "/kənˈviːniənt/ | adj. 方便的",
  "convey": "/kənˈveɪ/ | v. 传达；运输",
  "convince": "/kənˈvɪns/ | v. 使信服；说服",
  "cooperate": "/kəʊˈɒpəreɪt/ | v. 合作；配合",
  "cope": "/kəʊp/ | v. 应付；处理",
  "crucial": "/ˈkruːʃl/ | adj. 至关重要的",
  "cultivate": "/ˈkʌltɪveɪt/ | v. 培养；耕作",
  "curiosity": "/ˌkjʊəriˈɒsəti/ | n. 好奇心",
  "decline": "/dɪˈklaɪn/ | v./n. 下降；衰退；婉拒",
  "decorate": "/ˈdekəreɪt/ | v. 装饰",
  "decrease": "/dɪˈkriːs/ | v./n. 减少；下降",
  "dedicate": "/ˈdedɪkeɪt/ | v. 奉献；致力于",
  "defeat": "/dɪˈfiːt/ | v./n. 击败；失败",
  "defend": "/dɪˈfend/ | v. 保卫；辩护",
  "define": "/dɪˈfaɪn/ | v. 定义；限定",
  "deliver": "/dɪˈlɪvə(r)/ | v. 递送；发表；接生",
  "demand": "/dɪˈmɑːnd/ | v./n. 要求；需求",
  "demonstrate": "/ˈdemənstreɪt/ | v. 证明；演示",
  "deny": "/dɪˈnaɪ/ | v. 否认；拒绝",
  "depend": "/dɪˈpend/ | v. 依赖；取决于",
  "depress": "/dɪˈpres/ | v. 使沮丧；压低",
  "derive": "/dɪˈraɪv/ | v. 得到；源于",
  "describe": "/dɪˈskraɪb/ | v. 描述；形容",
  "deserve": "/dɪˈzɜːv/ | v. 应得；值得",
  "desire": "/dɪˈzaɪə(r)/ | n./v. 渴望；欲望",
  "despite": "/dɪˈspaɪt/ | prep. 尽管",
  "destination": "/ˌdestɪˈneɪʃn/ | n. 目的地",
  "destroy": "/dɪˈstrɔɪ/ | v. 破坏；毁灭",
  "determine": "/dɪˈtɜːmɪn/ | v. 决定；确定",
  "device": "/dɪˈvaɪs/ | n. 设备；装置",
  "devote": "/dɪˈvəʊt/ | v. 奉献；投入",
  "differ": "/ˈdɪfə(r)/ | v. 不同；相异",
  "digital": "/ˈdɪdʒɪtl/ | adj. 数字的",
  "dimension": "/daɪˈmenʃn/ | n. 维度；尺寸",
  "diminish": "/dɪˈmɪnɪʃ/ | v. 减少；削弱",
  "disaster": "/dɪˈzɑːstə(r)/ | n. 灾难",
  "discipline": "/ˈdɪsəplɪn/ | n. 纪律；学科",
  "discount": "/ˈdɪskaʊnt/ | n. 折扣",
  "discriminate": "/dɪˈskrɪmɪneɪt/ | v. 歧视；区分",
  "dismiss": "/dɪsˈmɪs/ | v. 解雇；不予考虑",
  "display": "/dɪˈspleɪ/ | v./n. 展示；显示",
  "distinguish": "/dɪˈstɪŋɡwɪʃ/ | v. 区分；辨别",
  "distribute": "/dɪˈstrɪbjuːt/ | v. 分配；分发",
  "disturb": "/dɪˈstɜːb/ | v. 打扰；扰乱",
  "diverse": "/daɪˈvɜːs/ | adj. 多样的；不同的",
  "domestic": "/dəˈmestɪk/ | adj. 国内的；家庭的",
  "dominate": "/ˈdɒmɪneɪt/ | v. 支配；主导",
  "dramatic": "/drəˈmætɪk/ | adj. 戏剧性的；巨大的",
  "eager": "/ˈiːɡə(r)/ | adj. 渴望的；热切的",
  "economical": "/ˌiːkəˈnɒmɪkl/ | adj. 节约的；经济的",
  "efficient": "/ɪˈfɪʃnt/ | adj. 高效的",
  "elaborate": "/ɪˈlæbərət/ | adj. 精心制作的；详尽的",
  "eliminate": "/ɪˈlɪmɪneɪt/ | v. 消除；淘汰",
  "embarrass": "/ɪmˈbærəs/ | v. 使尴尬",
  "emerge": "/iˈmɜːdʒ/ | v. 出现；浮现",
  "emphasis": "/ˈemfəsɪs/ | n. 强调；重点",
  "employ": "/ɪmˈplɔɪ/ | v. 雇用；使用",
  "enable": "/ɪˈneɪbl/ | v. 使能够",
  "encounter": "/ɪnˈkaʊntə(r)/ | v./n. 遭遇；偶遇",
  "encourage": "/ɪnˈkʌrɪdʒ/ | v. 鼓励",
  "enhance": "/ɪnˈhɑːns/ | v. 提高；增强",
  "enormous": "/ɪˈnɔːməs/ | adj. 巨大的",
  "ensure": "/ɪnˈʃʊə(r)/ | v. 确保；保证",
  "enthusiasm": "/ɪnˈθjuːziæzəm/ | n. 热情；热忱",
  "environment": "/ɪnˈvaɪrənmənt/ | n. 环境",
  "equip": "/ɪˈkwɪp/ | v. 装备；配备",
  "essential": "/ɪˈsenʃl/ | adj. 必要的；本质的",
  "establish": "/ɪˈstæblɪʃ/ | v. 建立；确立",
  "estimate": "/ˈestɪmeɪt/ | v./n. 估计；估价",
  "evaluate": "/ɪˈvæljueɪt/ | v. 评估；评价",
  "evidence": "/ˈevɪdəns/ | n. 证据",
  "evident": "/ˈevɪdənt/ | adj. 明显的",
  "evolve": "/iˈvɒlv/ | v. 进化；演变",
  "exaggerate": "/ɪɡˈzædʒəreɪt/ | v. 夸大；夸张",
  "examine": "/ɪɡˈzæmɪn/ | v. 检查；考试",
  "exceed": "/ɪkˈsiːd/ | v. 超过；超越",
  "exception": "/ɪkˈsepʃn/ | n. 例外",
  "excess": "/ɪkˈses/ | n. 过量 adj. 过量的",
  "exchange": "/ɪksˈtʃeɪndʒ/ | v./n. 交换；交流",
  "exclude": "/ɪkˈskluːd/ | v. 排除；不包括",
  "exhibit": "/ɪɡˈzɪbɪt/ | v. 展示 n. 展品",
  "expand": "/ɪkˈspænd/ | v. 扩大；扩展",
  "expectation": "/ˌekspekˈteɪʃn/ | n. 期望；预期",
  "expense": "/ɪkˈspens/ | n. 花费；开支",
  "experiment": "/ɪkˈsperɪmənt/ | n. 实验 v. 试验",
  "expert": "/ˈekspɜːt/ | n. 专家 adj. 熟练的",
  "exploit": "/ɪkˈsplɔɪt/ | v. 利用；开发；剥削",
  "explore": "/ɪkˈsplɔː(r)/ | v. 探索；探究",
  "expose": "/ɪkˈspəʊz/ | v. 暴露；揭露",
  "extend": "/ɪkˈstend/ | v. 延伸；扩大",
  "extensive": "/ɪkˈstensɪv/ | adj. 广泛的；大量的",
  "extent": "/ɪkˈstent/ | n. 程度；范围",
  "external": "/ɪkˈstɜːnl/ | adj. 外部的",
  "extinct": "/ɪkˈstɪŋkt/ | adj. 灭绝的",
  "extraordinary": "/ɪkˈstrɔːdnri/ | adj. 非凡的；杰出的",
  "facility": "/fəˈsɪləti/ | n. 设施；设备",
  "factor": "/ˈfæktə(r)/ | n. 因素；要素",
  "faculty": "/ˈfæklti/ | n. 全体教员；能力",
  "familiar": "/fəˈmɪliə(r)/ | adj. 熟悉的",
  "fascinate": "/ˈfæsɪneɪt/ | v. 使着迷",
  "fatigue": "/fəˈtiːɡ/ | n. 疲劳",
  "feature": "/ˈfiːtʃə(r)/ | n. 特征 v. 以……为特色",
  "finance": "/ˈfaɪnæns/ | n. 财政；金融",
  "flexible": "/ˈfleksəbl/ | adj. 灵活的；柔韧的",
  "fluctuate": "/ˈflʌktʃueɪt/ | v. 波动；起伏",
  "focus": "/ˈfəʊkəs/ | v./n. 集中；焦点",
  "forbid": "/fəˈbɪd/ | v. 禁止",
  "forecast": "/ˈfɔːkɑːst/ | v./n. 预测；预报",
  "fortunate": "/ˈfɔːtʃənət/ | adj. 幸运的",
  "foundation": "/faʊnˈdeɪʃn/ | n. 基础；基金会",
  "frequent": "/ˈfriːkwənt/ | adj. 频繁的",
  "frustrate": "/frʌˈstreɪt/ | v. 使沮丧；挫败",
  "fulfill": "/fʊlˈfɪl/ | v. 履行；实现",
  "function": "/ˈfʌŋkʃn/ | n. 功能 v. 运转",
  "fundamental": "/ˌfʌndəˈmentl/ | adj. 基本的；根本的",
  "generate": "/ˈdʒenəreɪt/ | v. 产生；生成",
  "generous": "/ˈdʒenərəs/ | adj. 慷慨的；大方的",
  "genuine": "/ˈdʒenjuɪn/ | adj. 真正的；真诚的",
  "gesture": "/ˈdʒestʃə(r)/ | n. 手势；姿态",
  "guarantee": "/ˌɡærənˈtiː/ | v./n. 保证；担保",
  "guilty": "/ˈɡɪlti/ | adj. 内疚的；有罪的",
  "habit": "/ˈhæbɪt/ | n. 习惯",
  "handle": "/ˈhændl/ | v. 处理；操作 n. 把手",
  "hardship": "/ˈhɑːdʃɪp/ | n. 艰难；困苦",
  "harmony": "/ˈhɑːməni/ | n. 和谐；融洽",
  "hesitate": "/ˈhezɪteɪt/ | v. 犹豫",
  "highlight": "/ˈhaɪlaɪt/ | v. 强调；突出 n. 亮点",
  "hinder": "/ˈhɪndə(r)/ | v. 阻碍；妨碍",
  "humble": "/ˈhʌmbl/ | adj. 谦逊的；卑微的",
  "identify": "/aɪˈdentɪfaɪ/ | v. 识别；确认",
  "ignore": "/ɪɡˈnɔː(r)/ | v. 忽视；不理睬",
  "illustrate": "/ˈɪləstreɪt/ | v. 说明；阐明；举例",
  "immigrate": "/ˈɪmɪɡreɪt/ | v. 移民",
  "impact": "/ˈɪmpækt/ | n. 影响；冲击",
  "implement": "/ˈɪmplɪment/ | v. 实施；执行",
  "imply": "/ɪmˈplaɪ/ | v. 暗示；意味着",
  "impose": "/ɪmˈpəʊz/ | v. 强加；征收",
  "impress": "/ɪmˈpres/ | v. 给……留下深刻印象",
  "improve": "/ɪmˈpruːv/ | v. 改进；提高",
  "incident": "/ˈɪnsɪdənt/ | n. 事件；事故",
  "incline": "/ɪnˈklaɪn/ | v. 倾向；倾斜",
  "income": "/ˈɪnkʌm/ | n. 收入",
  "increasingly": "/ɪnˈkriːsɪŋli/ | adv. 越来越多地",
  "indicate": "/ˈɪndɪkeɪt/ | v. 表明；指示",
  "individual": "/ˌɪndɪˈvɪdʒuəl/ | adj. 个人的 n. 个人",
  "induce": "/ɪnˈdjuːs/ | v. 引起；诱导",
  "inevitable": "/ɪnˈevɪtəbl/ | adj. 不可避免的",
  "infer": "/ɪnˈfɜː(r)/ | v. 推断",
  "influence": "/ˈɪnfluəns/ | n./v. 影响",
  "ingredient": "/ɪnˈɡriːdiənt/ | n. 成分；原料",
  "inhabit": "/ɪnˈhæbɪt/ | v. 居住于",
  "inherit": "/ɪnˈherɪt/ | v. 继承",
  "initial": "/ɪˈnɪʃl/ | adj. 最初的 n. 首字母",
  "initiative": "/ɪˈnɪʃətɪv/ | n. 主动性；倡议",
  "innovation": "/ˌɪnəˈveɪʃn/ | n. 创新；革新",
  "inspect": "/ɪnˈspekt/ | v. 检查；视察",
  "inspire": "/ɪnˈspaɪə(r)/ | v. 鼓舞；启发",
  "install": "/ɪnˈstɔːl/ | v. 安装",
  "instinct": "/ˈɪnstɪŋkt/ | n. 本能；直觉",
  "institute": "/ˈɪnstɪtjuːt/ | n. 学院；研究所",
  "instruct": "/ɪnˈstrʌkt/ | v. 指导；命令",
  "insurance": "/ɪnˈʃʊərəns/ | n. 保险",
  "integrate": "/ˈɪntɪɡreɪt/ | v. 整合；融入",
  "intense": "/ɪnˈtens/ | adj. 强烈的；紧张的",
  "intention": "/ɪnˈtenʃn/ | n. 意图；目的",
  "interact": "/ˌɪntərˈækt/ | v. 互动；相互作用",
  "interfere": "/ˌɪntəˈfɪə(r)/ | v. 干涉；妨碍",
  "internal": "/ɪnˈtɜːnl/ | adj. 内部的",
  "interpret": "/ɪnˈtɜːprɪt/ | v. 解释；口译",
  "interrupt": "/ˌɪntəˈrʌpt/ | v. 打断；中断",
  "interval": "/ˈɪntəvl/ | n. 间隔；幕间休息",
  "intervene": "/ˌɪntəˈviːn/ | v. 干预；介入",
  "invest": "/ɪnˈvest/ | v. 投资；投入",
  "investigate": "/ɪnˈvestɪɡeɪt/ | v. 调查",
  "involve": "/ɪnˈvɒlv/ | v. 涉及；使参与",
  "isolate": "/ˈaɪsəleɪt/ | v. 隔离；孤立",
  "issue": "/ˈɪʃuː/ | n. 问题；议题 v. 发行",
  "jealous": "/ˈdʒeləs/ | adj. 嫉妒的",
  "journal": "/ˈdʒɜːnl/ | n. 期刊；日志",
  "justify": "/ˈdʒʌstɪfaɪ/ | v. 证明……正当",
  "keen": "/kiːn/ | adj. 热衷的；敏锐的",
  "label": "/ˈleɪbl/ | n. 标签 v. 贴标签",
  "labor": "/ˈleɪbə(r)/ | n. 劳动；劳工",
  "landscape": "/ˈlændskeɪp/ | n. 风景；景观",
  "largely": "/ˈlɑːdʒli/ | adv. 主要地；很大程度上",
  "launch": "/lɔːntʃ/ | v. 发射；发起；推出",
  "leading": "/ˈliːdɪŋ/ | adj. 主要的；领先的",
  "leisure": "/ˈleʒə(r)/ | n. 闲暇；空闲",
  "liable": "/ˈlaɪəbl/ | adj. 有责任的；易于……的",
  "liberal": "/ˈlɪbərəl/ | adj. 自由的；开明的",
  "license": "/ˈlaɪsns/ | n. 执照；许可证",
  "likelihood": "/ˈlaɪklihʊd/ | n. 可能性",
  "limit": "/ˈlɪmɪt/ | n./v. 限制；界限",
  "literature": "/ˈlɪtrətʃə(r)/ | n. 文学；文献",
  "locate": "/ləʊˈkeɪt/ | v. 定位；位于",
  "logic": "/ˈlɒdʒɪk/ | n. 逻辑",
  "luxury": "/ˈlʌkʃəri/ | n. 奢侈；奢侈品",
  "maintain": "/meɪnˈteɪn/ | v. 维持；保养；主张",
  "majority": "/məˈdʒɒrəti/ | n. 大多数",
  "manifest": "/ˈmænɪfest/ | v. 显示；表明",
  "manipulate": "/məˈnɪpjuleɪt/ | v. 操纵；操作",
  "manufacture": "/ˌmænjuˈfæktʃə(r)/ | v./n. 制造",
  "margin": "/ˈmɑːdʒɪn/ | n. 边缘；利润；页边",
  "mature": "/məˈtʃʊə(r)/ | adj. 成熟的 v. 成熟",
  "measure": "/ˈmeʒə(r)/ | v. 测量 n. 措施",
  "mechanism": "/ˈmekənɪzəm/ | n. 机制；机械",
  "medium": "/ˈmiːdiəm/ | n. 媒介；手段 adj. 中等的",
  "mental": "/ˈmentl/ | adj. 心理的；精神的",
  "merit": "/ˈmerɪt/ | n. 优点；价值",
  "method": "/ˈmeθəd/ | n. 方法",
  "migrate": "/maɪˈɡreɪt/ | v. 迁移；迁徙",
  "military": "/ˈmɪlətri/ | adj. 军事的",
  "minimum": "/ˈmɪnɪməm/ | n./adj. 最小量；最小的",
  "minority": "/maɪˈnɒrəti/ | n. 少数；少数民族",
  "modify": "/ˈmɒdɪfaɪ/ | v. 修改；调整",
  "monitor": "/ˈmɒnɪtə(r)/ | v. 监控 n. 显示器",
  "moral": "/ˈmɒrəl/ | adj. 道德的 n. 寓意",
  "motivate": "/ˈməʊtɪveɪt/ | v. 激励；激发",
  "mutual": "/ˈmjuːtʃuəl/ | adj. 相互的；共同的",
  "negative": "/ˈneɡətɪv/ | adj. 消极的；负面的",
  "neglect": "/nɪˈɡlekt/ | v./n. 忽视；疏忽",
  "negotiate": "/nɪˈɡəʊʃieɪt/ | v. 谈判；协商",
  "neutral": "/ˈnjuːtrəl/ | adj. 中立的",
  "nevertheless": "/ˌnevəðəˈles/ | adv. 然而；不过",
  "notion": "/ˈnəʊʃn/ | n. 概念；观念",
  "numerous": "/ˈnjuːmərəs/ | adj. 众多的",
  "nurture": "/ˈnɜːtʃə(r)/ | v. 培育；养育",
  "obey": "/əˈbeɪ/ | v. 服从；遵守",
  "objective": "/əbˈdʒektɪv/ | n. 目标 adj. 客观的",
  "obligation": "/ˌɒblɪˈɡeɪʃn/ | n. 义务；责任",
  "observe": "/əbˈzɜːv/ | v. 观察；遵守；庆祝",
  "obstacle": "/ˈɒbstəkl/ | n. 障碍",
  "obtain": "/əbˈteɪn/ | v. 获得",
  "obvious": "/ˈɒbviəs/ | adj. 明显的",
  "occupy": "/ˈɒkjupaɪ/ | v. 占据；占用",
  "occur": "/əˈkɜː(r)/ | v. 发生；出现",
  "offend": "/əˈfend/ | v. 冒犯；得罪",
  "offer": "/ˈɒfə(r)/ | v./n. 提供；提议",
  "opportunity": "/ˌɒpəˈtjuːnəti/ | n. 机会",
  "oppose": "/əˈpəʊz/ | v. 反对",
  "optimistic": "/ˌɒptɪˈmɪstɪk/ | adj. 乐观的",
  "option": "/ˈɒpʃn/ | n. 选择；选项",
  "ordinary": "/ˈɔːdnri/ | adj. 普通的；平凡的",
  "organize": "/ˈɔːɡənaɪz/ | v. 组织",
  "origin": "/ˈɒrɪdʒɪn/ | n. 起源；出身",
  "outcome": "/ˈaʊtkʌm/ | n. 结果",
  "overcome": "/ˌəʊvəˈkʌm/ | v. 克服",
  "overlook": "/ˌəʊvəˈlʊk/ | v. 忽视；俯瞰",
  "overwhelm": "/ˌəʊvəˈwelm/ | v. 压倒；淹没",
  "participate": "/pɑːˈtɪsɪpeɪt/ | v. 参与；参加",
  "particular": "/pəˈtɪkjələ(r)/ | adj. 特定的；特别的",
  "passion": "/ˈpæʃn/ | n. 激情；热情",
  "peculiar": "/pɪˈkjuːliə(r)/ | adj. 奇怪的；特有的",
  "perceive": "/pəˈsiːv/ | v. 感知；理解",
  "perform": "/pəˈfɔːm/ | v. 表演；执行",
  "permanent": "/ˈpɜːmənənt/ | adj. 永久的",
  "persist": "/pəˈsɪst/ | v. 坚持；持续",
  "perspective": "/pəˈspektɪv/ | n. 观点；视角",
  "persuade": "/pəˈsweɪd/ | v. 说服；劝服",
  "phenomenon": "/fəˈnɒmɪnən/ | n. 现象",
  "physical": "/ˈfɪzɪkl/ | adj. 身体的；物理的",
  "pollution": "/pəˈluːʃn/ | n. 污染",
  "potential": "/pəˈtenʃl/ | adj. 潜在的 n. 潜力",
  "poverty": "/ˈpɒvəti/ | n. 贫穷",
  "precious": "/ˈpreʃəs/ | adj. 珍贵的",
  "predict": "/prɪˈdɪkt/ | v. 预测",
  "prefer": "/prɪˈfɜː(r)/ | v. 更喜欢",
  "prejudice": "/ˈpredʒudɪs/ | n. 偏见",
  "preliminary": "/prɪˈlɪmɪnəri/ | adj. 初步的",
  "preserve": "/prɪˈzɜːv/ | v. 保护；保存",
  "prevent": "/prɪˈvent/ | v. 阻止；预防",
  "previous": "/ˈpriːviəs/ | adj. 先前的",
  "primary": "/ˈpraɪməri/ | adj. 主要的；初级的",
  "principle": "/ˈprɪnsəpl/ | n. 原则；原理",
  "priority": "/praɪˈɒrəti/ | n. 优先；优先事项",
  "privilege": "/ˈprɪvəlɪdʒ/ | n. 特权；优惠",
  "procedure": "/prəˈsiːdʒə(r)/ | n. 程序；步骤",
  "process": "/ˈprəʊses/ | n. 过程 v. 处理",
  "produce": "/prəˈdjuːs/ | v. 生产；产生",
  "professional": "/prəˈfeʃənl/ | adj. 专业的 n. 专业人士",
  "prohibit": "/prəˈhɪbɪt/ | v. 禁止",
  "promote": "/prəˈməʊt/ | v. 促进；提升；推销",
  "proper": "/ˈprɒpə(r)/ | adj. 适当的；正确的",
  "property": "/ˈprɒpəti/ | n. 财产；性质",
  "proportion": "/prəˈpɔːʃn/ | n. 比例；部分",
  "propose": "/prəˈpəʊz/ | v. 提议；求婚",
  "prospect": "/ˈprɒspekt/ | n. 前景；可能性",
  "prosperity": "/prɒˈsperəti/ | n. 繁荣；兴旺",
  "protect": "/prəˈtekt/ | v. 保护",
  "protest": "/ˈprəʊtest/ | n./v. 抗议",
  "provide": "/prəˈvaɪd/ | v. 提供",
  "purchase": "/ˈpɜːtʃəs/ | v./n. 购买",
  "pursue": "/pəˈsjuː/ | v. 追求；从事",
  "qualify": "/ˈkwɒlɪfaɪ/ | v. 使合格；取得资格",
  "quantity": "/ˈkwɒntəti/ | n. 数量",
  "quote": "/kwəʊt/ | v./n. 引用；报价",
  "range": "/reɪndʒ/ | n. 范围；一系列",
  "rare": "/reə(r)/ | adj. 稀有的；罕见的",
  "react": "/riˈækt/ | v. 反应",
  "recover": "/rɪˈkʌvə(r)/ | v. 恢复；康复",
  "reduce": "/rɪˈdjuːs/ | v. 减少；降低",
  "refer": "/rɪˈfɜː(r)/ | v. 提及；参考",
  "reflect": "/rɪˈflekt/ | v. 反映；反思",
  "reform": "/rɪˈfɔːm/ | v./n. 改革",
  "refuse": "/rɪˈfjuːz/ | v. 拒绝",
  "regard": "/rɪˈɡɑːd/ | v. 认为；看待 n. 尊重",
  "region": "/ˈriːdʒən/ | n. 地区；区域",
  "register": "/ˈredʒɪstə(r)/ | v./n. 登记；注册",
  "regulate": "/ˈreɡjuleɪt/ | v. 调节；管理",
  "reinforce": "/ˌriːɪnˈfɔːs/ | v. 加强；强化",
  "reject": "/rɪˈdʒekt/ | v. 拒绝；排斥",
  "relate": "/rɪˈleɪt/ | v. 联系；叙述",
  "release": "/rɪˈliːs/ | v./n. 释放；发布",
  "relevant": "/ˈreləvənt/ | adj. 相关的",
  "relieve": "/rɪˈliːv/ | v. 缓解；减轻",
  "reluctant": "/rɪˈlʌktənt/ | adj. 不情愿的",
  "rely": "/rɪˈlaɪ/ | v. 依赖；信赖",
  "remark": "/rɪˈmɑːk/ | n./v. 评论；注意",
  "remarkable": "/rɪˈmɑːkəbl/ | adj. 显著的；非凡的",
  "remedy": "/ˈremədi/ | n. 补救办法；疗法",
  "remote": "/rɪˈməʊt/ | adj. 遥远的；偏远的",
  "remove": "/rɪˈmuːv/ | v. 移除；去除",
  "renew": "/rɪˈnjuː/ | v. 更新；续约",
  "represent": "/ˌreprɪˈzent/ | v. 代表；表示",
  "reputation": "/ˌrepjuˈteɪʃn/ | n. 名声；声誉",
  "require": "/rɪˈkwaɪə(r)/ | v. 需要；要求",
  "rescue": "/ˈreskjuː/ | v./n. 营救；救援",
  "research": "/rɪˈsɜːtʃ/ | n./v. 研究",
  "resemble": "/rɪˈzembl/ | v. 像；类似",
  "resist": "/rɪˈzɪst/ | v. 抵抗；抵制",
  "resolve": "/rɪˈzɒlv/ | v. 解决；决心",
  "resource": "/rɪˈsɔːs/ | n. 资源",
  "respond": "/rɪˈspɒnd/ | v. 回应；回答",
  "restore": "/rɪˈstɔː(r)/ | v. 恢复；修复",
  "restrict": "/rɪˈstrɪkt/ | v. 限制；约束",
  "retain": "/rɪˈteɪn/ | v. 保持；保留",
  "reveal": "/rɪˈviːl/ | v. 揭示；透露",
  "revenue": "/ˈrevənjuː/ | n. 收入；税收",
  "reverse": "/rɪˈvɜːs/ | v. 颠倒；逆转",
  "review": "/rɪˈvjuː/ | v./n. 复习；评论",
  "revise": "/rɪˈvaɪz/ | v. 修订；复习",
  "reward": "/rɪˈwɔːd/ | n. 奖励 v. 酬谢",
  "rigid": "/ˈrɪdʒɪd/ | adj. 严格的；僵硬的",
  "rival": "/ˈraɪvl/ | n. 对手 v. 与……竞争",
  "routine": "/ruːˈtiːn/ | n. 常规；例行公事",
  "rural": "/ˈrʊərəl/ | adj. 农村的",
  "sacrifice": "/ˈsækrɪfaɪs/ | n./v. 牺牲",
  "scale": "/skeɪl/ | n. 规模；刻度；天平",
  "scarce": "/skeəs/ | adj. 稀缺的；不足的",
  "scheme": "/skiːm/ | n. 计划；方案",
  "secure": "/sɪˈkjʊə(r)/ | adj. 安全的 v. 获得；保护",
  "seek": "/siːk/ | v. 寻找；寻求",
  "select": "/sɪˈlekt/ | v. 选择 adj. 精选的",
  "sensible": "/ˈsensəbl/ | adj. 明智的；合理的",
  "sensitive": "/ˈsensətɪv/ | adj. 敏感的",
  "separate": "/ˈsepəreɪt/ | v. 分离 adj. 分开的",
  "significant": "/sɪɡˈnɪfɪkənt/ | adj. 重要的；显著的",
  "similar": "/ˈsɪmələ(r)/ | adj. 相似的",
  "simplify": "/ˈsɪmplɪfaɪ/ | v. 简化",
  "simultaneous": "/ˌsɪmlˈteɪniəs/ | adj. 同时的",
  "sincere": "/sɪnˈsɪə(r)/ | adj. 真诚的",
  "situation": "/ˌsɪtʃuˈeɪʃn/ | n. 情况；形势",
  "skeptical": "/ˈskeptɪkl/ | adj. 怀疑的",
  "slight": "/slaɪt/ | adj. 轻微的；微小的",
  "solve": "/sɒlv/ | v. 解决",
  "sophisticated": "/səˈfɪstɪkeɪtɪd/ | adj. 复杂的；老练的",
  "source": "/sɔːs/ | n. 来源；源头",
  "specific": "/spəˈsɪfɪk/ | adj. 具体的；特定的",
  "sponsor": "/ˈspɒnsə(r)/ | n. 赞助商 v. 赞助",
  "stable": "/ˈsteɪbl/ | adj. 稳定的 n. 马厩",
  "statistics": "/stəˈtɪstɪks/ | n. 统计；统计学",
  "status": "/ˈsteɪtəs/ | n. 地位；状态",
  "steady": "/ˈstedi/ | adj. 稳定的；平稳的",
  "stimulate": "/ˈstɪmjuleɪt/ | v. 刺激；激励",
  "strategy": "/ˈstrætədʒi/ | n. 策略；战略",
  "strengthen": "/ˈstreŋθn/ | v. 加强",
  "stress": "/stres/ | n. 压力 v. 强调",
  "strive": "/straɪv/ | v. 努力；奋斗",
  "structure": "/ˈstrʌktʃə(r)/ | n. 结构 v. 构建",
  "struggle": "/ˈstrʌɡl/ | v./n. 挣扎；奋斗",
  "submit": "/səbˈmɪt/ | v. 提交；服从",
  "subsequent": "/ˈsʌbsɪkwənt/ | adj. 随后的",
  "substance": "/ˈsʌbstəns/ | n. 物质；实质",
  "substitute": "/ˈsʌbstɪtjuːt/ | n./v. 替代",
  "sufficient": "/səˈfɪʃnt/ | adj. 足够的",
  "suggest": "/səˈdʒest/ | v. 建议；暗示",
  "superior": "/suːˈpɪəriə(r)/ | adj. 更好的；上级的",
  "supplement": "/ˈsʌplɪment/ | n./v. 补充",
  "support": "/səˈpɔːt/ | v./n. 支持；支撑",
  "suppose": "/səˈpəʊz/ | v. 假设；认为",
  "suppress": "/səˈpres/ | v. 抑制；镇压",
  "surplus": "/ˈsɜːpləs/ | n./adj. 过剩；盈余的",
  "survey": "/ˈsɜːveɪ/ | n./v. 调查；审视",
  "survive": "/səˈvaɪv/ | v. 幸存；存活",
  "suspect": "/səˈspekt/ | v. 怀疑 n. 嫌疑人",
  "suspend": "/səˈspend/ | v. 暂停；悬挂",
  "sustain": "/səˈsteɪn/ | v. 维持；支撑",
  "symbol": "/ˈsɪmbl/ | n. 象征；符号",
  "sympathy": "/ˈsɪmpəθi/ | n. 同情",
  "tackle": "/ˈtækl/ | v. 处理；解决",
  "talent": "/ˈtælənt/ | n. 才能；人才",
  "target": "/ˈtɑːɡɪt/ | n. 目标 v. 瞄准",
  "temporary": "/ˈtemprəri/ | adj. 临时的",
  "tend": "/tend/ | v. 倾向；照料",
  "tension": "/ˈtenʃn/ | n. 紧张；张力",
  "terminal": "/ˈtɜːmɪnl/ | n. 终点站；终端 adj. 末期的",
  "territory": "/ˈterətri/ | n. 领土；领域",
  "theory": "/ˈθɪəri/ | n. 理论",
  "threat": "/θret/ | n. 威胁",
  "thrive": "/θraɪv/ | v. 兴旺；茁壮成长",
  "tolerate": "/ˈtɒləreɪt/ | v. 容忍；忍受",
  "tough": "/tʌf/ | adj. 艰难的；坚韧的",
  "trace": "/treɪs/ | v. 追踪；追溯 n. 痕迹",
  "tradition": "/trəˈdɪʃn/ | n. 传统",
  "transfer": "/trænsˈfɜː(r)/ | v./n. 转移；转学",
  "transform": "/trænsˈfɔːm/ | v. 改变；转化",
  "transmit": "/trænzˈmɪt/ | v. 传输；传播",
  "transport": "/trænˈspɔːt/ | v./n. 运输",
  "treat": "/triːt/ | v. 对待；治疗",
  "tremendous": "/trəˈmendəs/ | adj. 巨大的；极好的",
  "trend": "/trend/ | n. 趋势；潮流",
  "typical": "/ˈtɪpɪkl/ | adj. 典型的",
  "ultimate": "/ˈʌltɪmət/ | adj. 最终的；根本的",
  "undergo": "/ˌʌndəˈɡəʊ/ | v. 经历；经受",
  "underline": "/ˌʌndəˈlaɪn/ | v. 强调；在……下划线",
  "undertake": "/ˌʌndəˈteɪk/ | v. 承担；从事",
  "unique": "/juˈniːk/ | adj. 独特的；独一无二的",
  "universal": "/ˌjuːnɪˈvɜːsl/ | adj. 普遍的；通用的",
  "urban": "/ˈɜːbən/ | adj. 城市的",
  "urge": "/ɜːdʒ/ | v. 敦促 n. 冲动",
  "utilize": "/ˈjuːtəlaɪz/ | v. 利用",
  "vacant": "/ˈveɪkənt/ | adj. 空的；空缺的",
  "vague": "/veɪɡ/ | adj. 模糊的；含糊的",
  "valid": "/ˈvælɪd/ | adj. 有效的；合理的",
  "vanish": "/ˈvænɪʃ/ | v. 消失",
  "variety": "/vəˈraɪəti/ | n. 多样；种类",
  "vary": "/ˈveəri/ | v. 变化；不同",
  "vast": "/vɑːst/ | adj. 广阔的；巨大的",
  "vehicle": "/ˈviːəkl/ | n. 车辆；工具",
  "venture": "/ˈventʃə(r)/ | n. 风险事业 v. 冒险",
  "verify": "/ˈverɪfaɪ/ | v. 核实；验证",
  "version": "/ˈvɜːʃn/ | n. 版本；说法",
  "victim": "/ˈvɪktɪm/ | n. 受害者",
  "vigorous": "/ˈvɪɡərəs/ | adj. 精力充沛的",
  "violate": "/ˈvaɪəleɪt/ | v. 违反；侵犯",
  "virtual": "/ˈvɜːtʃuəl/ | adj. 虚拟的；实际上的",
  "virtue": "/ˈvɜːtʃuː/ | n. 美德；优点",
  "visible": "/ˈvɪzəbl/ | adj. 可见的；明显的",
  "vision": "/ˈvɪʒn/ | n. 视力；愿景",
  "vital": "/ˈvaɪtl/ | adj. 至关重要的",
  "vivid": "/ˈvɪvɪd/ | adj. 生动的；鲜明的",
  "volume": "/ˈvɒljuːm/ | n. 体积；音量；卷",
  "voluntary": "/ˈvɒləntri/ | adj. 自愿的",
  "welfare": "/ˈwelfeə(r)/ | n. 福利；福祉",
  "widespread": "/ˈwaɪdspred/ | adj. 广泛的；普遍的",
  "wisdom": "/ˈwɪzdəm/ | n. 智慧",
  "withdraw": "/wɪðˈdrɔː/ | v. 撤回；取款",
  "witness": "/ˈwɪtnəs/ | n. 目击者 v. 目睹",
  "worthwhile": "/ˌwɜːθˈwaɪl/ | adj. 值得的",
  "yield": "/jiːld/ | v. 产出；屈服 n. 产量",
};

// 本课生词映射（app.js 渲染时填充），格式：{ word: {phonetic, meaning} }
let CONTEXT_VOCAB = {};

function normalizeWord(w) {
  if (!w) return '';
  return String(w).toLowerCase().replace(/[^a-z'-]/g, '');
}

// 本地查词：先本课生词，再内置词库
function lookupLocal(word) {
  const w = normalizeWord(word);
  if (!w) return null;
  if (CONTEXT_VOCAB[w]) {
    const v = CONTEXT_VOCAB[w];
    return { word: w, phonetic: v.phonetic || '', meaning: v.meaning || '', source: '本课生词' };
  }
  if (BUILTIN_DICT[w]) {
    const parts = BUILTIN_DICT[w].split('|');
    return {
      word: w,
      phonetic: (parts[0] || '').trim(),
      meaning: (parts[1] || '').trim(),
      source: '四级核心词库',
    };
  }
  return null;
}

// 联网查英文词典（兜底）
async function lookupOnline(word) {
  try {
    const r = await fetch('https://api.dictionaryapi.dev/api/v2/entries/en/' + encodeURIComponent(word));
    if (!r.ok) return null;
    const data = await r.json();
    if (!Array.isArray(data) || !data[0]) return null;
    const e = data[0];
    const phonetic = e.phonetic || (e.phonetics && e.phonetics[0] && e.phonetics[0].text) || '';
    const meanings = e.meanings.map(function (m) {
      const defs = m.definitions.slice(0, 2).map(function (d) { return d.definition; }).join('；');
      return '<b>' + m.partOfSpeech + '</b> ' + defs;
    }).join('<br>');
    return { word: word, phonetic: phonetic, meaning: meanings, source: '在线词典（英文释义）' };
  } catch (err) {
    return null;
  }
}
